import { Montserrat } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { ClerkProvider } from '@clerk/nextjs';
import GlobalState from '@/context';

const montserrat = Montserrat({
  style: 'normal',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <GlobalState>
        <html lang="en">
          <body className={montserrat.className}>{children}</body>
        </html>
      </GlobalState>
    </ClerkProvider>
  );
}
